### PR TITLE
Wip reticule

### PR DESCRIPTION
**Pull request by jdgarita**
This PR implements new changes regarding the Scanner View.
Check the expected scenario in the link below.
Trello card: https://trello.com/c/bk4PGVL9/1010-android-reticule-scanner-view

### CODE REVIEW

**Comment by thitu** [comment]
@JUANDIEGOGARITA the test app in this library - will it build and show the new reticle?

**Comment by jdgarita** [comment]
hmmm not sure, I tested it using the Trusona app, just updating this reference in the app

**Comment by thitu** [comment]
I think we should make sure the test app works too

**Comment by jdgarita** [comment]
I just tested it and works fine.

**Comment by thitu** [comment]
👍

**Review by thitu — APPROVED** [review]

**Review by jorgelsalas — APPROVED** [review]

**Pull request merged**
